### PR TITLE
Fix CI to run tests properly in Chrome

### PR DESCRIPTION
**Pull request by gabrielgrant**
WIP

### CODE REVIEW

**Comment by gabrielgrant** [comment]
This mostly seems to have worked, except for a failure running in node. Not sure if there's a way to get this file with the details? https://travis-ci.org/ember-vr/ember-aframe-shim/jobs/383108944#L2951

But it seems like it's probably a problem with Node 4 not recognizing some newer syntax. Given node 4 [is no longer maintained](https://github.com/nodejs/Release), and, as of the next (imminent) release, (no longer supported by Ember](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md), are you ok removing it from the testing matrix?

**Comment by kellyselden** [comment]
My apologies. It looks like it was just a node 4 regression in some package instead of a Firefox/Chrome issue. Bumping the node version should be all that is necessary.

**Comment by gabrielgrant** [comment]
@kellyselden No worries, just submitted a PR doing the node version bump. Hopefully that will be enough to get the tests passing on Travis. From my understanding, though, it seems the changes in this PR may be needed as well (unless Travis has recently removed some of the config that used to be needed to get browsers running in their env?). If both changes are needed, I'll close that and add all the changes to get CI passing to this

**Comment by gabrielgrant** [comment]
Sweet, that seems to have been sufficient. Good to know this config is no longer neeed. Closing this.

**Pull request closed without merging**
